name: Daily Test Run

on:
  schedule:
    # Запуск щодня о 10:00 UTC (12:00 за київським часом)
    - cron: "0 10 * * *"
  workflow_dispatch: # Дозволяє запускати вручну

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true

      - name: Generate HTML report
        run: npx playwright show-report --host 0.0.0.0
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results (blob)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

  test-matrix:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [auth, guest, user]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run specific project tests
        run: npx playwright test --project=${{ matrix.project }}
        env:
          CI: true

      - name: Upload project results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 30

  notify:
    needs: [test, test-matrix]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Notify on success
        if: needs.test.result == 'success' && needs.test-matrix.result == 'success'
        run: |
          echo "✅ All tests passed successfully!"
          echo "Daily test run completed at $(date)"

      - name: Notify on failure
        if: needs.test.result == 'failure' || needs.test-matrix.result == 'failure'
        run: |
          echo "❌ Some tests failed!"
          echo "Please check the test results and artifacts."
          exit 1
